language: ruby
deploy:
  - provider: rubygems
    api_key:
      # ninech-bot
      secure: "EZlq+xcwr1ORQFC8PTqFLztaLOWznzn14HaB4katuxdcOrRYQFP9oNyDQdKnr3p8mtYdqLHBF45KUgYJD5gJNHS6sIWd5zHuEkBPG/S5qlkMFUhRJ33IF86PWtnjG6h3xT/bvjcmHBlrmB0vVz6N7JkYl0tRNuLG/9iXg7Zgk6+AjMwCBTe4qwJTDIbjUp5bURm8ycnDzGFgzY5MYrHvwJ7jtFvMd1SM5OgPi14XyQcn5oVb6Pgr9b/2qzv1V+9ixcVqsTagqLdpcpNFvIvs+SC/r03tggAEb2WiWIZyG5HcfPXoz4Pddqq+jx23+iPxFIenreI2cCMboCqXWah59KquM6bunOv8oyeGAXnMUMR4w//xxcxI4e19atOh9o1zg0doDeM+ym4S8uWtCUttI7VmrS/KE2wqqMUGgXbu68fO33CN+FISN/IH8xWCRW+2oZBcmzUTEE59b4aR2C9OkwJ7PrMC6bqaUrwy/Z+TLCr1n6aI3H4+/cMACqcPZoQn65G18ZH+YAMfNA/fBsHw2oAsy+G+/LWx7FMGNLXKxHVgd9hAWlrKDVCoETiYJMCZJLMxe5w7rT6n+IeHHLOoXgwxOYLdaJRcnXyBnLhGtwhmZFw4MidtJwknKkaU7JbMTimByc7AxgW5tLORmaukGS5A1q5G3RLBCWZianNeL8o="
    gem: audited-timeline
    on:
      tags: true
      repo: ninech/audited-timeline
    skip_cleanup: true
  - provider: releases
    api_key:
      # ninech-bot
      secure: "DS7lCx2dfWPmx/fUOR/yoypa09fYieHXHH92qCgI80pdEALE+ZYnEpqdt0TzEIwS7xtSSq53SUmfSP7vkmN2cWwJ8vYfAH3m8gJgyKdF+Z/qVwO6RIBG0JAK7ausS45KFkj6nOvzk/WzJ2MJZ1IcZIx5PAfWhl/BXHTE5bhHL8+48aFMbytAv55YqNlkRQKqzf4sFfSLsbGKcjncbidQ585QfktAcyTbqLtRT+2yE/cmkgxsoXKRxIF68gRFs8XXvWjtmYT8OFvzAwRZPQV9cLV3Hhhz0ZSSZI1NP/BlphFN31WIEybLziVXc2/wMqHYBQ/TDceJwj7E54jsUjryi5mjiA4qsbpBU6G62120H3ihWvVpbjQPWmHOjGwN5nhKftwSI9AxkD4JP8fM6FCayGCBo30mv7M+sAsv4BgSXqFls9hV6ypYDix4ZjIwqdaViAz7jMqjSIXgL3IDlQ3J85gfmHTFIfB+xDDJg96FzmoLn3JPINt7fkVjLBm480bFxpDMTcCIZzQJW7ILTirMo3tijrJviCVC1k27l71vSTYkPJ1CEAsEnxHRRsKdZRCI1RA9GkjOSjAqlN9+K6+rVab/QMo+B4stUQyUoVfapSWG5js1ryQQx/P0Aldijptir/x5/UMVkeBz+2dOhjbrN8srQkAoEJevy/frWTxjWZg="
    file: 'audited-timeline-*.gem'
    on:
      tags: true
      repo: ninech/audited-timeline
